import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen bg-gradient-to-r from-blue-900 via-blue-700 to-blue-500 ">
          <div className="flex pb-2 justify-center">
            <p className="text-4xl font-bold mt-5 ml-4 text-[#fff] font-mono">
              Non-maintainance MAB penalty calculator
            </p>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
