import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "@/context";
import Header from "./header/page";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-h-screen bg-gradient-to-r from-blue-900 via-blue-700 to-blue-500 ">
          <AuthProvider>
            <Header />
            <main className="container mx-auto px-4 sm:px-6 lg:px-8 py-8">
              <Toaster />
              {children}
            </main>
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
